name: "Docker Release"

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  docker-release:
    name: "Docker Release"
    if: startsWith(github.ref, 'refs/tags/')
    uses: dosquad/actions/.github/workflows/docker-release.yml@main
    secrets:
      docker_github_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      image: ghcr.io/dosquad/mock-github-oauth-server
      platforms: linux/amd64,linux/arm64
